"""
Unit tests for franka_fk_pose and _rot_to_axisangle.

All CPU-only, no GPU/checkpoint/simulator required.
Run from the worktree root:
    conda run -n vla-pilot pytest tests/unit/test_fk_and_axisangle.py -v

Reference values were generated by running the functions at known inputs and
cross-checked against Rodrigues' rotation formula.
"""
import numpy as np
import pytest

from core.rdt_action_converter import (
    _rot_to_axisangle,
    franka_fk_pose,
    FRANKA_Q_MIN,
    FRANKA_Q_MAX,
)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _rot_from_axisangle(axis: np.ndarray, angle: float) -> np.ndarray:
    """Rodrigues formula: axis (unit vector) × angle (rad) → 3×3 rotation."""
    axis = axis / (np.linalg.norm(axis) + 1e-12)
    K = np.array([
        [0.0,      -axis[2],  axis[1]],
        [axis[2],   0.0,     -axis[0]],
        [-axis[1],  axis[0],  0.0],
    ])
    return np.eye(3) + np.sin(angle) * K + (1.0 - np.cos(angle)) * (K @ K)


# ─────────────────────────────────────────────────────────────────────────────
# _rot_to_axisangle
# ─────────────────────────────────────────────────────────────────────────────

class TestRotToAxisAngle:

    def test_identity_returns_zero(self):
        """Identity rotation → zero axis-angle vector."""
        aa = _rot_to_axisangle(np.eye(3))
        np.testing.assert_allclose(aa, np.zeros(3), atol=1e-10)

    def test_output_shape(self):
        """Output is always a (3,) float vector."""
        aa = _rot_to_axisangle(np.eye(3))
        assert aa.shape == (3,)
        assert aa.dtype in (np.float32, np.float64)

    def test_90deg_about_x(self):
        """90° rotation about X-axis → axis-angle [π/2, 0, 0]."""
        R = _rot_from_axisangle(np.array([1.0, 0.0, 0.0]), np.pi / 2)
        aa = _rot_to_axisangle(R)
        np.testing.assert_allclose(aa, [np.pi / 2, 0.0, 0.0], atol=1e-7)

    def test_90deg_about_y(self):
        """90° rotation about Y-axis → axis-angle [0, π/2, 0]."""
        R = _rot_from_axisangle(np.array([0.0, 1.0, 0.0]), np.pi / 2)
        aa = _rot_to_axisangle(R)
        np.testing.assert_allclose(aa, [0.0, np.pi / 2, 0.0], atol=1e-7)

    def test_90deg_about_z(self):
        """90° rotation about Z-axis → axis-angle [0, 0, π/2]."""
        R = _rot_from_axisangle(np.array([0.0, 0.0, 1.0]), np.pi / 2)
        aa = _rot_to_axisangle(R)
        np.testing.assert_allclose(aa, [0.0, 0.0, np.pi / 2], atol=1e-7)

    def test_45deg_about_z(self):
        """45° rotation about Z → [0, 0, π/4]."""
        R = _rot_from_axisangle(np.array([0.0, 0.0, 1.0]), np.pi / 4)
        aa = _rot_to_axisangle(R)
        np.testing.assert_allclose(aa, [0.0, 0.0, np.pi / 4], atol=1e-7)

    @pytest.mark.parametrize("angle_deg", [30, 60, 90, 120, 150])
    @pytest.mark.parametrize("axis_vec", [
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    ])
    def test_magnitude_equals_angle(self, angle_deg, axis_vec):
        """||axis-angle|| must equal the rotation angle in radians."""
        angle = angle_deg * np.pi / 180.0
        axis = np.array(axis_vec, dtype=float)
        R = _rot_from_axisangle(axis, angle)
        aa = _rot_to_axisangle(R)
        np.testing.assert_allclose(np.linalg.norm(aa), angle, atol=1e-6,
                                   err_msg=f"||aa|| ≠ angle for {angle_deg}° about {axis_vec}")

    def test_arbitrary_axis_30deg(self):
        """30° about [1,1,0]/√2 matches axis×angle within 1e-8."""
        axis = np.array([1.0, 1.0, 0.0]) / np.sqrt(2.0)
        angle = np.pi / 6
        R = _rot_from_axisangle(axis, angle)
        aa = _rot_to_axisangle(R)
        np.testing.assert_allclose(aa, axis * angle, atol=1e-8)

    def test_result_direction_equals_axis(self):
        """Normalised result must equal the rotation axis for non-trivial angles."""
        axis = np.array([0.6, 0.8, 0.0])   # unit vector
        angle = np.pi / 3                   # 60°
        R = _rot_from_axisangle(axis, angle)
        aa = _rot_to_axisangle(R)
        recovered_axis = aa / (np.linalg.norm(aa) + 1e-12)
        np.testing.assert_allclose(recovered_axis, axis, atol=1e-6)

    def test_roundtrip_consistency(self):
        """R → aa → R' via Rodrigues must give the same R (within FP tolerance)."""
        axis = np.array([0.2, 0.9, 0.3])
        axis /= np.linalg.norm(axis)
        angle = 1.1
        R = _rot_from_axisangle(axis, angle)
        aa = _rot_to_axisangle(R)
        R_trip = _rot_from_axisangle(aa / (np.linalg.norm(aa) + 1e-12),
                                      float(np.linalg.norm(aa)))
        np.testing.assert_allclose(R_trip, R, atol=1e-6)

    def test_small_angle_no_exception(self):
        """Near-identity rotation (1e-5 rad) must not raise and return a small vector."""
        angle = 1e-5
        R = _rot_from_axisangle(np.array([0.0, 0.0, 1.0]), angle)
        aa = _rot_to_axisangle(R)   # must not raise
        assert np.linalg.norm(aa) < 1e-4, f"Expected small aa, got ||aa||={np.linalg.norm(aa)}"

    def test_180deg_degenerate_documented(self):
        """
        180° rotation (sin=0) is a known degenerate case.

        The current implementation uses the skew-symmetric part of R to extract
        the axis, which vanishes when angle=π. The function silently returns a
        zero vector instead of the true axis × π.

        This test documents the observed behaviour so any future fix will be
        noticed; it is NOT asserting the zero-return is correct.
        """
        R180x = np.diag([1.0, -1.0, -1.0])   # 180° about X
        aa = _rot_to_axisangle(R180x)
        # Current behaviour: returns zeros (wrong but stable — no exception)
        assert aa.shape == (3,), "Must return a (3,) vector"
        assert not np.any(np.isnan(aa)), "Must not return NaN"
        assert not np.any(np.isinf(aa)), "Must not return Inf"
        # NOTE: the correct answer is [π, 0, 0]; this returns [0, 0, 0].
        # If this assertion fails in the future, the function was fixed — update test.
        np.testing.assert_allclose(aa, np.zeros(3), atol=1e-6,
                                   err_msg="Degenerate 180° behaviour changed — update test")


# ─────────────────────────────────────────────────────────────────────────────
# franka_fk_pose
# ─────────────────────────────────────────────────────────────────────────────

class TestFrankaFkPose:

    # ── Shape / type ──────────────────────────────────────────────────────────

    def test_output_shapes(self):
        """FK returns pos:(3,) and rot:(3,3)."""
        pos, rot = franka_fk_pose(np.zeros(7))
        assert pos.shape == (3,), f"pos shape {pos.shape}"
        assert rot.shape == (3, 3), f"rot shape {rot.shape}"

    def test_output_dtype_float(self):
        """Output arrays should be floating-point."""
        pos, rot = franka_fk_pose(np.zeros(7))
        assert np.issubdtype(pos.dtype, np.floating)
        assert np.issubdtype(rot.dtype, np.floating)

    # ── Rotation matrix invariants ────────────────────────────────────────────

    @pytest.mark.parametrize("q", [
        np.zeros(7),
        np.array([0.1, -0.5, 0.2, -2.0, 0.1, 2.5, 0.3]),
        np.array([0.0, -np.pi/4, 0.0, -3*np.pi/4, 0.0, np.pi/2, np.pi/4]),
    ])
    def test_rotation_is_orthogonal(self, q):
        """R.T @ R must be identity (≤ 1e-12 residual)."""
        _, rot = franka_fk_pose(q)
        residual = np.max(np.abs(rot.T @ rot - np.eye(3)))
        assert residual < 1e-12, f"Rotation not orthogonal: residual={residual:.2e}"

    @pytest.mark.parametrize("q", [
        np.zeros(7),
        np.array([0.1, -0.5, 0.2, -2.0, 0.1, 2.5, 0.3]),
    ])
    def test_rotation_determinant_is_one(self, q):
        """det(R) must equal +1 (proper rotation, not reflection)."""
        _, rot = franka_fk_pose(q)
        det = float(np.linalg.det(rot))
        assert abs(det - 1.0) < 1e-10, f"det(R)={det:.8f}, expected 1.0"

    # ── Known reference positions ─────────────────────────────────────────────

    def test_zero_joints_known_position(self):
        """
        FK at all-zero joints must match the reference position [0.088, -0.068, 0.226].
        This value was computed from the bundled _FRANKA_DH parameters and serves
        as a regression guard against DH-table modifications.
        """
        pos, _ = franka_fk_pose(np.zeros(7))
        expected = np.array([0.088, -0.068, 0.226])
        np.testing.assert_allclose(pos, expected, atol=1e-3,
                                   err_msg="FK at q=0 deviated from reference — DH table changed?")

    def test_ready_pose_known_position(self):
        """
        FK at Franka 'ready' pose [0, -π/4, 0, -3π/4, 0, π/2, π/4]
        must match the reference position [0.2234, 0.4696, 0.3196].
        """
        q_ready = np.array([0.0, -np.pi/4, 0.0, -3*np.pi/4, 0.0, np.pi/2, np.pi/4])
        pos, _ = franka_fk_pose(q_ready)
        expected = np.array([0.2234, 0.4696, 0.3196])
        np.testing.assert_allclose(pos, expected, atol=1e-3,
                                   err_msg="FK at ready pose deviated from reference")

    def test_home_pose_known_position(self):
        """
        FK at [0, 0, 0, -π/2, 0, π/2, 0] must match [−0.296, 0.316, 0.226].
        """
        q_home = np.array([0.0, 0.0, 0.0, -np.pi/2, 0.0, np.pi/2, 0.0])
        pos, _ = franka_fk_pose(q_home)
        expected = np.array([-0.296, 0.316, 0.226])
        np.testing.assert_allclose(pos, expected, atol=1e-3)

    # ── Continuity & smoothness ───────────────────────────────────────────────

    @pytest.mark.parametrize("joint_idx", range(7))
    def test_continuity_small_perturbation(self, joint_idx):
        """Small Δq (1e-3 rad) on any joint must produce small ΔEEF (< 0.01 m)."""
        q0 = np.zeros(7)
        q1 = q0.copy(); q1[joint_idx] += 1e-3
        pos0, _ = franka_fk_pose(q0)
        pos1, _ = franka_fk_pose(q1)
        delta = np.linalg.norm(pos1 - pos0)
        assert delta < 0.01, (
            f"Joint {joint_idx}: Δq=1e-3 → ΔEEF={delta:.4f} m (expected < 0.01 m)"
        )

    def test_determinism(self):
        """Same joint config must produce identical results on repeated calls."""
        q = np.array([0.3, -0.2, 0.5, -1.5, 0.1, 2.1, 0.7])
        pos1, rot1 = franka_fk_pose(q)
        pos2, rot2 = franka_fk_pose(q)
        np.testing.assert_array_equal(pos1, pos2, err_msg="pos not deterministic")
        np.testing.assert_array_equal(rot1, rot2, err_msg="rot not deterministic")

    def test_different_configs_produce_different_eef(self):
        """Two distinct joint configs must yield distinct EEF positions."""
        q1 = np.zeros(7)
        q2 = np.array([0.5, 0.2, -0.3, -1.5, 0.1, 2.0, 0.8])
        pos1, _ = franka_fk_pose(q1)
        pos2, _ = franka_fk_pose(q2)
        assert np.linalg.norm(pos1 - pos2) > 0.01, "Different configs gave identical EEF"

    # ── Physical workspace sanity ─────────────────────────────────────────────

    def test_eef_above_base_at_zero(self):
        """EEF z-coordinate at q=0 must be positive (arm points upward)."""
        pos, _ = franka_fk_pose(np.zeros(7))
        assert pos[2] > 0.1, f"EEF z={pos[2]:.3f} m, expected > 0.1 m at q=0"

    def test_eef_z_positive_at_ready_pose(self):
        """EEF z at ready pose must be above the table (z > 0.2 m)."""
        q = np.array([0.0, -np.pi/4, 0.0, -3*np.pi/4, 0.0, np.pi/2, np.pi/4])
        pos, _ = franka_fk_pose(q)
        assert pos[2] > 0.2, f"EEF z={pos[2]:.3f} m at ready pose"

    def test_workspace_y_reachable_at_ready(self):
        """At the ready pose, y-extent must be within plausible Franka reach (~0.9 m)."""
        q = np.array([0.0, -np.pi/4, 0.0, -3*np.pi/4, 0.0, np.pi/2, np.pi/4])
        pos, _ = franka_fk_pose(q)
        assert abs(pos[1]) < 0.9, f"EEF y={pos[1]:.3f} m seems out of Franka workspace"

    # ── Joint limit coverage ─────────────────────────────────────────────────

    def test_no_exception_at_joint_limits(self):
        """FK must not raise for any combination of Franka joint limits."""
        for sign in (+1, -1):
            q = np.where(sign > 0, FRANKA_Q_MAX, FRANKA_Q_MIN)
            # Some limit combinations may be kinematically weird but must not raise
            try:
                pos, rot = franka_fk_pose(q)
                assert pos.shape == (3,)
            except Exception as e:
                pytest.fail(f"FK raised {type(e).__name__} at joint limits (sign={sign}): {e}")

    def test_no_exception_at_arbitrary_valid_config(self):
        """FK must not raise for an arbitrary joint config within limits."""
        rng = np.random.default_rng(42)
        for _ in range(20):
            q = rng.uniform(FRANKA_Q_MIN, FRANKA_Q_MAX)
            pos, rot = franka_fk_pose(q)
            assert pos.shape == (3,)
            assert rot.shape == (3, 3)

    # ── Integration: FK + _rot_to_axisangle pipeline ─────────────────────────

    def test_consecutive_fk_delta_axisangle_magnitude(self):
        """
        For two consecutive joint configs with small Δq, the axis-angle of the
        incremental rotation must be small (< 0.5 rad).
        This exercises the actual converter pipeline used in rdt_action_converter.
        """
        q0 = np.array([0.0, -np.pi/4, 0.0, -3*np.pi/4, 0.0, np.pi/2, np.pi/4])
        q1 = q0 + np.array([0.05, -0.03, 0.02, 0.04, -0.01, 0.03, 0.02])
        _, rot0 = franka_fk_pose(q0)
        _, rot1 = franka_fk_pose(q1)
        delta_rot = rot1 @ rot0.T
        aa = _rot_to_axisangle(delta_rot)
        angle = np.linalg.norm(aa)
        assert angle < 0.5, (
            f"Incremental rotation ||aa||={angle:.4f} rad for small Δq — unexpectedly large"
        )
